#!/bin/bash

# first step: git clone https://github.com/ezequielcinalli/dotfiles.git

# update packages
pacman -Syu

# install packages
pacman -S firefox zsh keepassxc github-cli neovim ttf-font-awesome ttf-meslo-nerd-font-powerlevel10k nodejs npm feh picom

# setup zsh default as default shell
chsh -s $(which zsh)

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# install zsh-vi-mode plugin for oh-my-zsh
git clone https://github.com/jeffreytse/zsh-vi-mode \
  $ZSH_CUSTOM/plugins/zsh-vi-mode

# install powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# enter to repository and copy files to home folder
cd dotfiles
cp -r .config/ ~/
cp .gitconfig .p10k.zsh .zshrc .xprofile ~/
